#!/bin/bash
#
#	/etc/rc.d/init.d/echo-server
#
# Starts the echo-server daemon
#
# chkconfig: 2345 95 5
# description: runs the echo server daemon
# processname: echo-server

# Source function library.
. /etc/init.d/functions

test -x /usr/sbin/echo-server || exit 0

prog="echo-server"
RETVAL=0
PIDFILE=/var/run/echo-server.pid


start() {
	# Check if echo-server is already running
	if [ ! -f /var/lock/subsys/echo-server ]; then
	    echo -n $"Starting $prog: "
	    daemon /usr/sbin/echo-server --log-pid
	    RETVAL=$?
	    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/echo-server
	    echo
	fi
	return $RETVAL
}

stop() {
	echo -n $"Stopping $prog: "
	killproc -p $PIDFILE
	RETVAL=$?
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/echo-server
	echo
        return $RETVAL
}


restart() {
	stop
	start
}	

reload() {
	restart
}	

status_at() {
 	status -p $PIDFILE $prog
}

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
reload|restart)
	restart
	;;
condrestart)
	if [ -f /var/lock/subsys/echo-server ]; then
	    restart
	fi
	;;
status)
	status_at
	;;
*)
	echo $"Usage: $0 {start|stop|restart|condrestart|status}"
	exit 1
esac

exit $?
exit $RETVAL
